title = "Matthieu Etchegoyen"
baseURL = "https://etchegom.github.io/"
theme = "hugo-resume"
languageCode = "fr-fr"
PygmentsCodeFences = true
PygmentsCodeFencesGuessSyntax = true
PygmentsStyle = "monokai"
enableGitInfo = false
defaultContentLanguage = "en"

[params]
address = "Cestas, France"
email = "etchegom@gmail.com"
favicon = "/favicon.ico"
firstName = "Matthieu"
lastName = "Etchegoyen"
phone = "+33603547110"
profileImage = "img/avatar.jpg"
showEducation = true
showExperience = true
showOpenSource = false
showProjects = false
showPublications = false
showQr = false
showSkills = true
coloredSkills = true
showCertifications = false
showSocialization = true

[params.google]

[params.google.analytics]
trackerID = ""

[[params.handles]]
link = "https://www.linkedin.com/in/matthieu-etchegoyen-1729205a/"
name = "LinkedIn"

[[params.handles]]
link = "https://github.com/etchegom"
name = "GitHub"

[outputs]
home = ["HTML", "JSON"]

[taxonomies]
tag = "tags"
